[package]
name = "pngme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc = "3.0"
byteorder = "1.3.4"
itertools = "0.10"
clap = { version = "4.4.18", features = ["derive"] }
